"""add chapter project relation

Revision ID: 1ff58c4f51ff
Revises: 6c09d73e567f
Create Date: 2026-07-08 13:33:44.311282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff58c4f51ff'
down_revision: Union[str, None] = '6c09d73e567f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chapters', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.drop_column('chapters', 'project_id')
    # ### end Alembic commands ###
