"""add project chapter relationship

Revision ID: 211ddf7610a4
Revises: 9cf6ce1bf21f
Create Date: 2026-07-08 14:04:10.645792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211ddf7610a4'
down_revision: Union[str, None] = '9cf6ce1bf21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
