"""add chapter project relation

Revision ID: 9cf6ce1bf21f
Revises: 1ff58c4f51ff
Create Date: 2026-07-08 13:35:14.880698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cf6ce1bf21f'
down_revision: Union[str, None] = '1ff58c4f51ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
